//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleGastosResidenciais.Application.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleGastosResidenciais.Application.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria não encontrada..
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORY_NOT_FOUND.
        /// </summary>
        public static string CategoryNotFoundCode {
            get {
                return ResourceManager.GetString("CategoryNotFoundCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição é obrigatória..
        /// </summary>
        public static string DescriptionError {
            get {
                return ResourceManager.GetString("DescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição deve ter no máximo 100 caracteres..
        /// </summary>
        public static string DescriptionLengthError {
            get {
                return ResourceManager.GetString("DescriptionLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Idade deve ser maior que zero. .
        /// </summary>
        public static string EmptyAgeError {
            get {
                return ResourceManager.GetString("EmptyAgeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id da categoria é obrigatório..
        /// </summary>
        public static string EmptyCategoryIdError {
            get {
                return ResourceManager.GetString("EmptyCategoryIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome não pode ser nulo..
        /// </summary>
        public static string EmptyNameError {
            get {
                return ResourceManager.GetString("EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id da pessoa é obrigatório..
        /// </summary>
        public static string EmptyPersonIdError {
            get {
                return ResourceManager.GetString("EmptyPersonIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor deve ser maior que zero..
        /// </summary>
        public static string EmptyValueError {
            get {
                return ResourceManager.GetString("EmptyValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro, tente novamente em alguns minutos..
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNAL_ERROR.
        /// </summary>
        public static string InternalErrorCode {
            get {
                return ResourceManager.GetString("InternalErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa não encontrada.
        /// </summary>
        public static string PersonNotFound {
            get {
                return ResourceManager.GetString("PersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSON_NOT_FOUND.
        /// </summary>
        public static string PersonNotFoundCode {
            get {
                return ResourceManager.GetString("PersonNotFoundCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A finalidade informada é inválida..
        /// </summary>
        public static string PurposeError {
            get {
                return ResourceManager.GetString("PurposeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A finalidade da categoria não pode ter diferente do tipo de transação..
        /// </summary>
        public static string TransactionInvalidCategory {
            get {
                return ResourceManager.GetString("TransactionInvalidCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_PURPOSE.
        /// </summary>
        public static string TransactionInvalidCategoryCode {
            get {
                return ResourceManager.GetString("TransactionInvalidCategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa menor de 18 anos não pode ter receita..
        /// </summary>
        public static string TransactionMinorIncomeNotAllowed {
            get {
                return ResourceManager.GetString("TransactionMinorIncomeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCOME_NOT_ALLOWED.
        /// </summary>
        public static string TransactionMinorIncomeNotAllowedCode {
            get {
                return ResourceManager.GetString("TransactionMinorIncomeNotAllowedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação não encontrada..
        /// </summary>
        public static string TransactionNotFound {
            get {
                return ResourceManager.GetString("TransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do tipo de transação informado é invalido..
        /// </summary>
        public static string TransactionTypeError {
            get {
                return ResourceManager.GetString("TransactionTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSACTION_NOT_FOUND.
        /// </summary>
        public static string TreansactionNotFoundCode {
            get {
                return ResourceManager.GetString("TreansactionNotFoundCode", resourceCulture);
            }
        }
    }
}
